import "normalize.css"
import "./styles/index.scss"
import "./components/form.ts"
import "./components/TimeTable/timetable.ts"
import "./components/TimeTable/popup.ts"
import "./components/map.ts"
import "./components/nav.ts"
import "./components/particles.ts"